CREATE TABLE FINANCEIRO (
	ID INT IDENTITY (1,1) NOT NULL,
	TIPO_PAGAMENTO CHAR (1) NOT NULL,
	DESCRICAO VARCHAR (100) NOT NULL,
   	VENCIMENTO DATE NOT NULL,
   	CARTAO VARCHAR (16),
   	BANDEIRA VARCHAR (20),
   	STATUS VARCHAR (10) NOT NULL,
   	CONSTRAINT PK_FINANCEIRO PRIMARY KEY (ID)
);

CREATE TABLE USUARIO (
	ID INT IDENTITY (1,1) NOT NULL,
	USARNAME VARCHAR (50) NOT NULL,
	SENHA VARCHAR (20) NOT NULL,
	DATA_CRIACAO DATE NOT NULL,
	CONSTRAINT PK_USUARIO PRIMARY KEY (ID),
);

CREATE TABLE CLIENTE (
	ID INT IDENTITY(1,1) NOT NULL,
	NOME_TITULAR VARCHAR(100) NOT NULL,
	EMAIL VARCHAR (100) NOT NULL,
	CPF VARCHAR (11) NOT NULL,
	ID_FINANCEIRO INT NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID),
	CONSTRAINT FK_CLIENTE_FINANCEIRO FOREIGN KEY (ID_FINANCEIRO)
	REFERENCES DBO.FINANCEIRO (ID)
);

ALTER TABLE CLIENTE 
	ADD CONSTRAINT FK_CLIENTE_USUARIO FOREIGN KEY (ID_USUARIO)
	REFERENCES DBO.USUARIO (ID);
	
CREATE TABLE CADASTRO (
	ID INT IDENTITY (1,1) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	TELEFONE VARCHAR(11) NOT NULL,
	ENDERECO VARCHAR (100) NOT NULL,
	NUMERO VARCHAR (100) NOT NULL,
	COMPLEMENTO VARCHAR (100),
	BAIRRO VARCHAR(100) NOT NULL,
	CIDADE VARCHAR (100) NOT NULL,
	UF VARCHAR (2) NOT NULL,
	CEP VARCHAR (8) NOT NULL,
	CONSTRAINT PK_CADASTRO PRIMARY KEY (ID),
	CONSTRAINT FK_CADASTRO_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID)
);

CREATE TABLE VIDEO (
   	ID INT IDENTITY(1,1) NOT NULL,
   	TITULO VARCHAR(100) NOT NULL,
   	TIPO VARCHAR (12) NOT NULL,
   	CONSTRAINT PK_VIDEO PRIMARY KEY(ID)
);

DROP TABLE SERIE  ;

CREATE TABLE FILME (
	ID INT IDENTITY (1,1) NOT NULL,
	ID_VIDEO INT NOT NULL,
	TITULO VARCHAR (100) NOT NULL,
	SINOPSE VARCHAR(450) NOT NULL,
	DURACAO TIME NOT NULL,
   	DIRETOR VARCHAR(100) NOT NULL,
   	GENERO VARCHAR(100) NOT NULL,
   	ANO_LANCAMENTO VARCHAR (4) NOT NULL,
   	PAIS VARCHAR (20) NOT NULL,
   	CLASSIFICACAO VARCHAR (5) NOT NULL,
   	CONSTRAINT PK_FILME PRIMARY KEY (ID),
   	CONSTRAINT FK_FILME_VIDEO FOREIGN KEY (ID)
   	REFERENCES DBO.VIDEO (ID)
);
-- TABELA VIDEO CRIADA

CREATE TABLE SERIE (
	ID INT IDENTITY(1,1) NOT NULL,
	ID_VIDEO INT NOT NULL,
	TITULO VARCHAR(100) NOT NULL,
	SINOPSE VARCHAR (450) NOT NULL,
	GENERO VARCHAR(100) NOT NULL,
	QTD_TEMPORADA INT,
	NUMERO_EP INT,
	ANO VARCHAR (4) NOT NULL,
	PAIS VARCHAR(100) NOT NULL,
	CLASSIFICACAO VARCHAR (5) NOT NULL,
	CONSTRAINT PK_SERIE PRIMARY KEY(ID),
	CONSTRAINT FK_SERIE_VIDEO FOREIGN KEY (ID)
   	REFERENCES DBO.VIDEO (ID)
);

CREATE TABLE DOCUMENTARIO (
	ID INT IDENTITY(1,1) NOT NULL,
	ID_VIDEO INT NOT NULL,
	TITULO VARCHAR(200) NOT NULL,
	SINOPSE VARCHAR (450) NOT NULL,
	GENERO VARCHAR(100),
	QTD_TEMPORADA INT,
	NUMERO_EP INT,
	ANO VARCHAR (4) NOT NULL,
	PAIS VARCHAR(100) NOT NULL,
	CLASSIFICACAO VARCHAR (5) NOT NULL,
	DURACAO TIME(5) NOT NULL,
	CONSTRAINT PK_DOCUMENTARIO PRIMARY KEY(ID),
	CONSTRAINT FK_DOCUMENTARIO_VIDEO FOREIGN KEY (ID)
   	REFERENCES DBO.VIDEO (ID)
);

DROP TABLE DOCUMENTARIO;

CREATE TABLE LISTA (
	ID INT IDENTITY (1,1) NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_FILME INT,
	ID_SERIE INT,
	ID_DOCUMENTARIO INT,
	AVALALIACAO VARCHAR (2)
	CONSTRAINT PK_LISTA PRIMARY KEY (ID),
	CONSTRAINT FK_LISTA_USARIO FOREIGN KEY (ID)
	REFERENCES DBO.USUARIO (ID),
	CONSTRAINT FK_LISTA_FILME FOREIGN KEY (ID)
	REFERENCES DBO.FILME (ID),
	CONSTRAINT FK_LISTA_SERIE FOREIGN KEY (ID)
	REFERENCES DBO.SERIE (ID),
	CONSTRAINT FK_LISTA_DOCUMENTARIO FOREIGN KEY (ID)
	REFERENCES DBO.DOCUMENTARIO (ID)
);

ALTER TABLE USUARIO 
	DROP COLUMN ID_LISTA;

ALTER TABLE STREAMING_.dbo.USUARIO DROP CONSTRAINT FK_USUARIO_LISTA;

DROP TABLE LISTA;

ALTER TABLE USUARIO
	ADD CONSTRAINT FK_USUARIO_LISTA FOREIGN KEY (ID_LISTA)
	REFERENCES DBO.LISTA (ID);
